### ISSUE TITLE
Error using zigpy-cli

### ISSUE THREAD

**Issue by lbuque** [zigpy/zigpy-cli#21]
I have a jn5169 usb dongle for which I flashed [zigate](https://github.com/fairecasoimeme/ZiGatev2/releases/download/v3.22/ZiGatev2-322.bin) firmware.

Trying to use zigpy-cli, I got the following error, how should I use it properly?

```powershell
PS D:\Workspace\zigpy-cli> zigpy radio zigate COM12 info
Traceback (most recent call last):
  File "C:\Users\lyy\AppData\Local\Programs\Python\Python310\Scripts\zigpy-script.py", line 33, in <module>
    sys.exit(load_entry_point('zigpy-cli==0.0.1', 'console_scripts', 'zigpy')())
  File "C:\Users\lyy\AppData\Local\Programs\Python\Python310\Scripts\zigpy-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\lyy\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "C:\Users\lyy\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\lyy\AppData\Local\Programs\Python\Python310\lib\site-packages\zigpy_cli\__main__.py", line 1, in <module>
    import zigpy_cli.ota  # noqa: F401
  File "C:\Users\lyy\AppData\Local\Programs\Python\Python310\lib\site-packages\zigpy_cli\ota.py", line 7, in <module>
    from zigpy.ota.image import ElementTagId, parse_ota_image
ImportError: cannot import name 'parse_ota_image' from 'zigpy.ota.image' (C:\Users\lyy\AppData\Local\Programs\Python\Python310\lib\site-packages\zigpy\ota\image.py)
```

**Comment by puddly** [comment]
How did you install it?

**Comment by lbuque** [comment]
```console
$ pip --version
pip 22.1.1 from C:\Users\lyy\AppData\Local\Programs\Python\Python310\lib\site-packages\pip (python 3.10)
$ python --version
Python 3.10.1
$ pip install git+https://github.com/zigpy/zigpy-cli.git
$ pip install zigpy-zigate==0.5.1
```

**Comment by puddly** [comment]
zigpy-zigate==0.5.1 was released almost three years ago, it's not compatible with zigpy-cli. Uninstall it and install the latest version.

**Comment by lbuque** [comment]
I installed the latest version of zigpy-zigate and got new errors.

![image](https://user-images.githubusercontent.com/46518962/199166921-d90295b3-4b7f-4bb6-9e10-68f5045942b5.png)

**Comment by Kochise** [comment]
Don't post picture, post wall of text that can be indexed by internal and external search engines.
